apiVersion: apps/v1
kind: Deployment
metadata:
  name: openresty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openresty
  template:
    metadata:
      labels:
        app: openresty
    spec:
      containers:
      - image: openresty-prometheus_openresty:latest
        imagePullPolicy: Never
        name: openresty
        ports:
          - containerPort: 8080
            protocol: TCP
