apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - image: openresty-prometheus_example:latest
        imagePullPolicy: Never
        name: example
        ports:
          - containerPort: 4000
            protocol: TCP
